trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build and Push Docker Image'
  steps:
  - task: Docker@2
    displayName: 'Build and Push'
    inputs:
      containerRegistry: 'miContenedorRegistry'  # Reemplaza con el nombre de tu registro de contenedores
      repository: 'miAppService'  # Reemplaza con el nombre que desees
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: 'latest'

- job: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Build
  steps:
  - task: AzureRmWebAppDeployment@4
    displayName: 'Azure App Service Deploy'
    inputs:
      azureSubscription: 'miAzureSubscription'  # Reemplaza con el nombre de tu suscripción de Azure
      ConnectedServiceName: 'miAzureServiceConnection'  # Reemplaza con el nombre de tu conexión de servicio de Azure
      appType: 'webAppContainer'
      WebAppName: 'miAppServiceName'  # Reemplaza con el nombre de tu App Service
      DockerNamespace: 'miContenedorRegistry.azurecr.io'  # Reemplaza con tu espacio de nombres de contenedor
      DockerRepository: 'miAppService'  # Reemplaza con el nombre que hayas usado para el repositorio
      DockerImageTag: '$(Build.SourceBranchName)-$(Build.BuildId)'
